### ISSUE TITLE
create 34 layers of resnet

### ISSUE THREAD

**Issue by kaishijeng** [XiaozhiChen/resnet-generator#1]
Xiaozhi,

   If I want to create resnet-34, network, should I just change # of layers from 50 to 34  in resnet50.def below:
# number of layers

50

**Comment by XiaozhiChen** [comment]
@kaishijeng To define a network architecture, you should follow Table 1 in the [Deep Residual Learning paper](http://arxiv.org/pdf/1512.03385v1.pdf) to configure a .def file.

Just added [resnet34.def](https://github.com/XiaozhiChen/resnet-generator/blob/master/resnet34.def).

**Comment by kaishijeng** [comment]
Thanks
